sudo: required
dist: trusty

os:
- osx
- linux

env:
- NODE_ENV=prod

node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache
language: node_js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8