platform:
  - x64

image: Visual Studio 2015

environment:
  nodejs_version: "8"
  matrix:
    - NODE_ENV: "prod"
      win_runtime: win-x64
      arch: x64
      plat: win32

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - npm --version
  - yarn --version
  - yarn config set child-concurrency 1
  - yarn 
  - yarn add windows-build-tools --global


build_script:
  - node --version
  - yarn --version
